package com.ess.portal.constants;

public enum AuditActionType {
    LOGIN,
    LOGOUT,
    REFRESH_TOKEN,
    CREATE_EMPLOYEE,
    UPDATE_EMPLOYEE,
    DELETE_EMPLOYEE,
    CHECK_IN,
    CHECK_OUT,
    CREATE_LEAVE,
    PROCESS_LEAVE,
    CREATE_EXPENSE,
    PROCESS_EXPENSE,
    CREATE_TRAVEL,
    PROCESS_TRAVEL,
    CREATE_REIMBURSEMENT,
    PROCESS_REIMBURSEMENT,
    CREATE_ASSET,
    PROCESS_ASSET,
    GENERATE_PAYROLL,
    SYSTEM_CONFIG_CHANGE
}
